# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-02 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_schedule_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Instructor')),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='generic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.GenericSection'),
        ),
        migrations.AlterUniqueTogether(
            name='genericsection',
            unique_together=set([('course', 'instructor')]),
        ),
    ]
